### ISSUE TITLE
ValueError: ('hydrationfreeenergy_freesolv', 'does not match to available values. Please double check.')

### ISSUE THREAD

**Issue by LiuCMU** [gmum/huggingmolecules#14]
Hi, 

I tried to run `quick_tour.py` under the `huggingmolecules` directory, but it gave the following error message:
```
(huggingmolecules) zhen@precision:~/huggingmolecules$ python quick_tour.py
WARNING:root:Argument blacklist is deprecated. Please use denylist.
WARNING:root:Argument blacklist is deprecated. Please use denylist.
WARNING:root:Argument blacklist is deprecated. Please use denylist.
WARNING:root:Argument blacklist is deprecated. Please use denylist.
WARNING:root:Argument blacklist is deprecated. Please use denylist.
['lipophilicity_astrazeneca', 'solubility_aqsoldb', 'caco2_wang', 'hia_hou', 'pgp_broccatelli', 'bioavailability_ma', 'vdss_lombardo', 'cyp2c19_veith', 'cyp2d6_veith', 'cyp3a4_veith', 'cyp1a2_veith', 'cyp2c9_veith', 'cyp2c9_substrate_carbonmangels', 'cyp2d6_substrate_carbonmangels', 'cyp3a4_substrate_carbonmangels', 'bbb_martins', 'ppbr_az', 'half_life_obach', 'clearance_hepatocyte_az', 'clearance_microsome_az']
Traceback (most recent call last):
  File "quick_tour.py", line 28, in <module>
    train_dataloader, _, _ = get_data_loaders(featurizer,
  File "/home/zhen/huggingmolecules/experiments/src/training/training_utils.py", line 169, in get_data_loaders
    split = get_data_split(task_name=task_name, dataset_name=dataset_name)
  File "/home/zhen/miniconda3/envs/huggingmolecules/lib/python3.8/site-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/zhen/miniconda3/envs/huggingmolecules/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/zhen/miniconda3/envs/huggingmolecules/lib/python3.8/site-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/zhen/huggingmolecules/experiments/src/training/training_utils.py", line 211, in get_data_split
    split = _get_data_split_from_tdc(task_name, dataset_name, assay_name,
  File "/home/zhen/huggingmolecules/experiments/src/training/training_utils.py", line 231, in _get_data_split_from_tdc
    data = task(name=dataset_name, label_name=assay_name)
  File "/home/zhen/miniconda3/envs/huggingmolecules/lib/python3.8/site-packages/tdc/single_pred/dataloader.py", line 38, in __init__
    super().__init__(name, path, label_name, print_stats,
  File "/home/zhen/miniconda3/envs/huggingmolecules/lib/python3.8/site-packages/tdc/single_pred/single_pred_dataset.py", line 17, in __init__
    entity1, y, entity1_idx = property_dataset_load(name, path, label_name, dataset_names)
  File "/home/zhen/miniconda3/envs/huggingmolecules/lib/python3.8/site-packages/tdc/utils.py", line 141, in property_dataset_load
    name = download_wrapper(name, path, dataset_names)
  File "/home/zhen/miniconda3/envs/huggingmolecules/lib/python3.8/site-packages/tdc/utils.py", line 44, in download_wrapper
    name = fuzzy_search(name, dataset_names)
  File "/home/zhen/miniconda3/envs/huggingmolecules/lib/python3.8/site-packages/tdc/utils.py", line 37, in fuzzy_search
    s =  get_closet_match(dataset_names, name)[0]
  File "/home/zhen/miniconda3/envs/huggingmolecules/lib/python3.8/site-packages/tdc/utils.py", line 734, in get_closet_match
    raise ValueError(test_token,
ValueError: ('hydrationfreeenergy_freesolv', 'does not match to available values. Please double check.')
  In call to configurable 'data' (<function get_data_split at 0x7fc43fa588b0>)
```
Could you please take a look? 

 BTW, I didn't see the `'hydrationfreeenergy_freesolv'` dataset when running the `quick_tour.py` file. Do you know where does the program store the downloaded dataset? Thank you very much!

**Comment by panpiort8** [comment]
huggingmolecules uses Therapeutics Datasets Common [package](https://github.com/mims-harvard/TDC), which seems to be currently bugged. I've opened an [issue](https://github.com/mims-harvard/TDC/issues/94). I hope they'll fixed it. Meanwhile I suggest downgrading PyTDC package to 0.1.8 version.

**Comment by panpiort8** [comment]
According to https://github.com/mims-harvard/TDC/issues/94#issuecomment-899225730, the issue will be fixed in the next TDC release. Answering your second question: the dataset file should be stored in the default TDC dataset storage directory (which, to my knowledge, is simply: `./data` ).
